nette/database

src/Database/Connection.php, src/Database/Context.php, src/Database/DriverException.php, src/Database/Drivers/MsSqlDriver.php, src/Database/Drivers/MySqlDriver.php, src/Database/Drivers/OciDriver.php, src/Database/Drivers/OdbcDriver.php, src/Database/Drivers/PgSqlDriver.php, src/Database/Drivers/SqliteDriver.php, src/Database/Drivers/SqlsrvDriver.php, src/Database/ISupplementalDriver.php, src/Database/ResultSet.php, src/Database/Table/Selection.php, src/Database/exceptions.php, tests/Database/Connection.exceptions.mysql.phpt, tests/Database/Connection.exceptions.phpt, tests/Database/Connection.exceptions.postgre.phpt, tests/Database/Connection.exceptions.sqlite.phpt, tests/Database/Connection.lazy.phpt, tests/Database/ResultSet.exceptions.mysql.phpt, tests/Database/ResultSet.exceptions.postgre.phpt, tests/Database/ResultSet.exceptions.sqlite.phpt
Inspired at http://www.doctrine-project.org
Some notes:
- exception names are taken from [Doctrine](http://apigen.juzna.cz/doc/doctrine/dbal/tree.html) (which are probably taken from Oracle/Java)
- I think that fine-granularity is required for "runtime" exceptions (ConstraintViolationException and its descendants), not for "logic" exceptions (syntax errors, table not found, etc)
- the separation between DriverException and ServerException is IMHO not needed. (It can be added in future with no BC break)
- `new PDO` throws bad exceptions in sense that getCode returns driver-specific error code instead of SQLSTATE error code as stated in documentation. (`$errorInfo` is NULL).
- `ISupplementalDriver::convertException` is static to allow handle exceptions occured by `new PDO`. But I think that …
=> Added custom exceptions

src/Database/Table/Selection.php, tests/Database/Table/Table.ref().phpt
Using structure like in https://github.com/nette/database/blob/master/tests/Database/files/mysql-nette_test1.sql and doing this:
$table = $context->table('book');
foreach ($table as $row) {
$translator = $row->ref('author', 'translator_id');
}
These queries are performed:
SELECT * FROM `book`
SELECT * FROM `author` WHERE (`id` IN (11, 12))
SELECT * FROM `author` WHERE (`id` IN (11, 12))
i.e. authors are needlessly refetched.
It does this both on master and 2.3.0 (PHP 5.5.9-1ubuntu4.6, MySQL 5.5.41-0ubuntu0.14.04.1).
It all goes down to https://github.com/nette/database/blob/master/src/Database/Table/Selection.php#L849 - the NULL key is never stored, so it is never found and performs a needless fetch.
The solution would be either to remember the NULL key on first fetch, or never fetch on …
=> Selection::getReferencedTable always reloads when $row[$column] is NULL

src/Database/Table/SqlBuilder.php, tests/Database/Table/SqlBuilder.addWhere().phpt
Problem is related only for drivers that support subqueries (like postgres).
Without this fix, selection $x with parameter in having can't be used as parameter in where of selection $y.
It end with error becouse selection $x is converted to sql and apended as subquery to where part of $y. As subquery contains complete SQL of $x, all parameters of $x must be added to $y. Actually, only parameters of where are added to $y.
=> SqlBuilder: Selection as parameter - all parameters must be added to where

src/Database/Table/Selection.php, tests/Database/Table/Table.related().caching.phpt
Without this patch, query inside cycle can affect result of getting related rows.. See test for example
=> Selection: Related prototype depends on specific cache key

src/Database/Table/Selection.php, tests/Database/Table/bugs/Selection.emptyResultSet.phpt
Selection refetch invalidates data but not references
=> cache invalidation bug

src/Database/Structure.php, tests/Database/Structure.phpt, tests/Database/Table/Selection.get().phpt, tests/Database/Table/bugs/bug49.phpt
- Fixes exceptions when trying to access to not existing table.
- When table not exists in cache, it try to reload structure like in case with foreign keys.
Fixes #79
=> Fixed missing table exception

src/Database/Table/Selection.php, tests/Database/Table/Selection.fetchField().phpt
I don't understand why `fetchField` wasn't added to `Selection` earlier. I am missing it here every day. Hope this will be accepted.
I wanted to create some tests for Selection too, but I can't get existing tests running. Testers show me this: http://i.imgur.com/13EzLhg.png But I am sure that I have pdo installed and enabled.
=> Added fetchField function to Selection

src/Database/Table/SqlBuilder.php, tests/Database/Table/SqlBuilder.addWhere().phpt, tests/Database/Table/SqlBuilder.parseJoins().phpt, tests/Database/Table/Table.backjoin.phpt, tests/Database/Table/Table.join.phpt
Oracle fails on `ORA-00905: missing keyword` when `AS` keyword is used.
When removed works on MySQL and Oracle. Please test other databases.
=> SqlBuilder: Remove "AS" keyword in JOINs

src/Database/Table/Selection.php, tests/Database/Table/bugs/ZeroPrimaryKey.phpt
If is there in row with primary key value "0", it could broke results
See http://forum.nette.org/cs/23838-nette-database-problem-s-nactenim-zaznamu (CZ).
I'm not sure how to write tests in nette database, but i tried write falling test and i wrote fix for that.
=> Selection: fixed bug with zero in primary key

src/Database/Drivers/SqlsrvDriver.php, tests/Database/SqlPreprocessor.phpt
When MS SQL save to datetime column, format 'Y-m-d H:i:s' is dependent on the SET LANGUAGE and SET DATETIME. Therefore it is better to use ISO 8601 format.
Documentation https://msdn.microsoft.com/en-us/library/ms187819.aspx says
The advantage in using the ISO 8601 format is that it is an international standard with unambiguous specification. Also, this format is not affected by the SET DATEFORMAT or SET LANGUAGE setting.
=> SqlsrvDriver::formatDateTime(): format datetime by ISO 8601

src/Database/Table/SqlBuilder.php, tests/Database/Table/SqlBuilder.addAlias().phpt
In previous patch, there was little mistake that checking of table name do not reflect specified column name (for example :book(translator) was evaluated exactly as :book).
There is also fix of test for postgres (@dg removes schema and now it's failing)
=> Improved unique table name detection

src/Database/Table/GroupedSelection.php, src/Database/Table/Selection.php, src/Database/Table/SqlBuilder.php
I was debugging export of products becase it takes too much time. At blackfire.io I found that 20% of all time takes resolving cache keys. Problem was with repeated parsing of query parts with regular expressions, that is not necessary for getting cache key. This patch can saves lot of time if you working with large datasets...
=> Performance > It prevents multiple parse of query parts by regular expresions

src/Database/Table/Selection.php, tests/Database/Table/Selection.whereOr().phpt
- feature
- documentation - needed: nette/web-content#404
- BC break - no
This feature will make creating the OR-ed where conditions easier by passing an (associative) array as its parameter.
=> Selection: added new method whereOr

src/Database/Table/SqlBuilder.php
Hi,
I've prepared this pull request as solution for issue #120. It add support for limit in update and delete queries in MySQL as desribed in documentation http://dev.mysql.com/doc/refman/5.7/en/update.html + http://dev.mysql.com/doc/refman/5.7/en/delete.html.
It add new constants to ISupplementalDriver SUPPORT_UPDATE_LIMIT and SUPPORT_DELETE_LIMIT so each driver can define support. If it's not supported, then is throw same exception as before.
=> Add support for limit in update and delete queries for MySQL driver

src/Database/Drivers/SqliteDriver.php
Sqlite stores datetime as integer/unix_timestamp, so handle it as unix timestamp.
=> Sqlite: fixed datetime column type

tests/Database/Connection.getInsertId().postgre.phpt
- bug fix? yes [nette forum](https://forum.nette.org/cs/27827-padaji-testy-pro-postgresql)
- BC break? no
Hi,
i run test for postgresql and than fail and i found in php [changelog](http://php.net/ChangeLog-5.php#5.6.26) the behavior was changed like php 7.0.11+.
=> Fix php version range for Connection::getLastInsertId().

appveyor.yml
- bug fix? yes
- BC break? no
Still not working as expected, but I think it's appveyor fault (SQL servers don't start). In any case, it's at least some progress. I spent lot of time with this, so I hope it won't be useless.
=> appveyor: upgrade php to version 7.1

src/Database/Connection.php, src/Database/Context.php, src/Database/IRowContainer.php, src/Database/ResultSet.php, src/Database/Table/ActiveRow.php, src/Database/Table/IRowContainer.php, src/Database/Table/Selection.php, tests/Database/Context.transaction.phpt, tests/Database/ResultSet.fetch().phpt, tests/Database/ResultSet.fetchField().phpt, tests/Database/Table/Selection.fetch().phpt, tests/Database/Table/Selection.fetchField().phpt, tests/Database/Table/Table.related().phpt
- bug fix? no
- new feature? yes
- BC break? yes
Since this is v3.0, I believe it's time to fix this old issue. It would be more logical if `fetch()` and `fetchField()` methods returned `NULL` instead of `FALSE`.
Why? If you have for example form factory with `create()` method with optinal parameter:
```php
class FormFactory
{
public function create(IRow $row = NULL) {}
}
```
Now you need to distinguish result from `fetch()` method like this:
```php
$this->formFactory->create($repository->fetch() ?: NULL);
```
After this change, result of `fetch()` could be passed directly to similar methods.
I also added `fetchField()` method to `IRowContainer`.
=> ResultSet: change fetch() and fetchField() methods result from FALSE to NULL

src/Database/Table/GroupedSelection.php, src/Database/Table/Selection.php
- bug fix? yes
- BC break? no
Aggregation function may return float, not just int. Only exception is `COUNT()`.
=> Fixed return types on aggregation functions

src/Database/Drivers/SqliteDriver.php
- bug fix? Closes #164
- BC break? no
Just fix the regular expression for finding autoincrement column in SQLite table.
I don't know if this is only SQLite 3.11.0 issue, but it uses "`" as quote character for column and table names, so autoincrement column definition looks like this:
`id` INTEGER NULL PRIMARY KEY AUTOINCREMENT
=> SqliteDriver::getColumns() fix regexp for autoincrement recognition [Closes #164]

src/Database/SqlPreprocessor.php, tests/Database/SqlPreprocessor.phpt
- bug fix? yes
- BC break? no
- doc PR: nette/docs#???  no
Issue: #171
=> SqlPreprocessor: throw exception if mode does not respond values

src/Database/Table/SqlBuilder.php
- bug fix? no
- new feature? yes
- BC break? no
- doc PR: later if accepted
Hi,
this PR adds support for UPDATE with ORDER BY.
This is good when you have sequnce column and you want to increment tail values in this column.
SQL for this action:
```sql
UPDATE myTable SET sort_order = sort_order + 1 WHERE sort_order > 100 ORDER BY sort_order DESC
```
Current approach is to write own query, as stated above.
WIP: I will add test and doc for this.
=> Support UPDATE with ORDER BY

src/Database/Table/SqlBuilder.php
- bug fix? yes  #181 
- BC break? no
=> SqlBuilder: sort all tables in parseJoinConditions (#181)

src/Database/ResultSet.php, src/Database/Table/Selection.php, tests/Database/ResultSet.normalizeRow.postgre.phpt
Postgre returns timestamps with timezone according to timezone currently
set for connection. If timezone for connection is not set, it uses default
timezone which can differ between systems.
- bug fix? yes
- BC break? no
=> ResultSet::normalizeRow(): fixed test when Postgre default TZ is not UTC

src/Database/Table/ActiveRow.php, src/Database/Table/ColumnAccessCache.php, src/Database/Table/GroupedSelection.php, src/Database/Table/ReferenceCache.php, src/Database/Table/Selection.php, tests/Database/Table/Table.cache.phpt
- bug fix? no
- new feature? yes
- BC break? no
@dg Cache implementation is a long term problem in `NDBT`. While this is definitely not perfect, it's a starting point from which I would like to continue making `NDBT` code more clear, which wil help in future development. I spent two days with this, so I hope you appreciate it. Also, if you agree, I can maintain this repo as we spoken on NettCamp. There is lot for review and merge.
=>  Selection: moved caching related functionality to separate classes

src/Database/Connection.php, src/Database/Drivers/MySqlDriver.php
Used query parameters instead of string concatenation of statement and parameters.
=> MySqlDriver: used query parameters in initialize

src/Database/Table/GroupedSelection.php
- bug fix? yes
- BC break? no
The $ref variable could have null value and in PHP 7.2 parameter in count can only be an array or an object implements Countable
=> PHP 7.2 fixed parameter passed to count

src/Database/Drivers/MySqlDriver.php
- bug fix? yes
- BC break? no
When you used PDO::ATTR_CASE option for MySQL connection Exception was thrown: Cannot read an undeclared column. Fix includes functions `getColumns(string $table)`, `getIndexes(string $table)`, `getForeignKeys(string $table)`
=> MySqlDriver: Fix PDO::ATTR_CASE

src/Database/Table/SqlBuilder.php, tests/Database/Table/SqlBuilder.addWhere().phpt
- bug fix
- BC break? no
Old behaviour causes InvalidArgumentException with error "Column operator does not accept array argument."
=> SqlBuilder: Fixed condition with Selection as one of more argument

src/Database/Helpers.php
If you call ResultSet::dump with null as column value, it will raise TypeError, so $col should be retyped to string, as htmlspecialchars expects string.
- bug fix
- BC break? no
=> Fixed dump issue with non-string values

src/Database/Table/Selection.php
- bug fix / new feature?
- BC break? no
Selection::current changed from `bool|ActiveRow` to specifier `false|ActiveRow`
=> Selection::current return row or false

src/Database/Table/Selection.php, tests/Database/Table/bugs/bug216.phpt
- bug fix #216 
- BC break? no
Changes the order of method calls in Selection::insert, so that getPrimarySequence and getPrimaryAutoincrementKey methods are called before actual query. Without this edit calling of these methods can spoil PDO:lastInsertId by database query for building Structure cache, which results in not obtaining new inserted ActiveRow.
This fail usualy happened on first insert query when used with StaticConvetions.
=> Fixed Selection::insert spoiling PDO:lastInsertId

src/Database/Table/SqlBuilder.php, tests/Database/Table/SqlBuilder.parseJoinConditions().phpt
- bug fix
- BC break? no
Fixed loading arguments for left join conditions specified for referencing tables (before this pull reguest it loads arguments correctly only for related tables)
=> SqlBuilder: Fixed loading arguments for left join conditions

src/Database/ResultSet.php, tests/Database/ResultSet.normalizeRow.mysql.phpt
Because with native prepared statements in MySQL, floats are returned as floats, not strings like with emulated prepares
- bug fix?  #227
- BC break? no
- doc PR: no
Fixes #227
=> ResultSet: only format strings as floats

src/Database/ResultSet.php
- bug fix
- BC break? most likely not
Work around an PHP bug, where mysql query with boolean parameters and disabled emulated prepare-statements fails silently. 
Bool value is interepreted incorrectly, more information in php bugtracker thread:
https://bugs.php.net/bug.php?id=38546
There is currently work being done in fixing the issue on the PHP end.
=> PDO, query with boolean parameters fails silently

src/Database/Structure.php, tests/Database/Structure.phpt, tests/Database/Structure.schemas.phpt
- bug fix: yes
- BC break: no (strictly yes - now foreign keys returned by driver should have name - all implementations of drivers in Nette have it that way, but some custom drivers could be problematic from that point of view)
This fixes bug #170.
The idea of that fix is that we can prefer FKs with less columns over FKs with more columns - this was exactly the point of #170.
=> Fix for bug 170

tests/Database/Table/bugs/bug170.phpt, tests/Database/files/mysql-bug170.sql
- bug fix: yes (not fixed, only failing test)
- BC break: no
This is failing test for issue #170
=> Added test for bug 170

src/Database/Table/Selection.php
bug fix
Oprava typu parametru u limit funkce, jelikož ne vždy chceme mít nějaký limit a pokud si napíšeme vrstvu na práci s datama, která může mít limit INT nebo NULL. Navíc uvnitř funkce se limit setuje a tam už null je null povolen.
=> Update param type in limit function

src/Bridges/DatabaseTracy/ConnectionPanel.php, src/Bridges/DatabaseTracy/templates/ConnectionPanel.panel.phtml, src/Database/Helpers.php
- new feature
- BC break - no
Hi, I tried to improve the highlighting of different types of SQL. This is quite useful in long outputs. What do you think?
=> Tracy panel - Highlight INSERT|UPDATE|DELETE

src/Database/Drivers/PgSqlDriver.php
Would be nice to release soon, so it is possible to use driver for Postgres v12. Thanks.
- bug fix
- BC break? no
Same issue was reported and fixed in https://github.com/vrana/adminer/pull/367
=> Column adsrc was removed in Postgres v12

src/Database/Helpers.php, tests/Database/Helpers.dumpSql.phpt
- bug fix
- BC break? no
This is just UI bug fix.
I found that `Helpers::dumpSql()` has problem with bool parameters.
Bool parameters are processed in last step and casted to `(string)`.
Problem is that `(string) FALSE` is empty string and not 0.
Because of that is `dumpSql()` able to generate invalid sql like this:
```
WHERE (`user`.`deleted` = OR `user`.`deleted` IS NULL)
```
instead of valid:
```
WHERE (`user`.`deleted` = 0 OR `user`.`deleted` IS NULL)
```
=> Helpers: Fix dumpSql() for bool parameters

src/Bridges/DatabaseTracy/templates/ConnectionPanel.panel.phtml, src/Database/Helpers.php
- new feature
- BC break? no
I would like the processing time to be displayed in color for each query. It is then easy to find slow questions and focus on them.
Some example:
Thanks!
=> ConnectionPanel: Added performance colors

src/Database/Drivers/MySqlDriver.php
As MySQL/MariaDB clearly does support subqueries.
This enables proper building of queries like...
```php
$table('table_a')
->where(
'table_a.column_one IN',
$table('table_b')->select('value')
)
```
... without executing the inner query first.
See https://dev.mysql.com/doc/refman/8.0/en/subqueries.html
and https://mariadb.com/kb/en/subqueries/
- bug fix / new feature? _Both, I think._
- BC break? _Who knows._
=> MySqlDriver driver knows about subqueries now.

src/Database/Table/GroupedSelection.php, src/Database/Table/Selection.php, src/Database/Table/SqlBuilder.php, tests/Database/Explorer/Explorer.aggregation.phpt
- bug fix
- BC break? Added optional parameter to method aggregate in Selection (signature change)
This fixes wrong results of aggregate functions applied on selection with group and having conditions. Previously aggregate of all rows even that not matching having conditions were returned.
=> Fixed aggregations when group by and having conditions are used

tests/Database/Connection.transaction.phpt
I think it is because the SQLServer uses empty string as a name for `SELECT count(*)` column and empty name is prohibited so the result `Row` has no columns at all.
https://github.com/nette/database/blob/f534aa7261b5603618cd327b902fb07194f6554f/src/Database/ResultSet.php#L187-L192
=> tests: fix sqlsrv tests

src/Database/Drivers/SqliteDriver.php
- bug 
- BC break: no
Hi, 
When I import data from files to sqlite3 database I got following error:
```
src/Database/Drivers/SqliteDriver.php:229
Trying to access array offset on value of type null
```
One thing is interesting. My colleague on OSX process import successfully without error.
```
nette/database v2.4.11
sqlite3 version: 3.27.2
OS: Linux
```
When I dump  **$keys[$row[‚id‘]]** before line 229 I get:
```
{
"name": 0,
"local": "key",
"table": "cache",
"foreign": null,
"onDelete": "CASCADE",
"onUpdate": "NO ACTION"
}
```
Code dont assume foreign is null.
https://forum.nette.org/cs/35537-nette-database-a-sqlite3-trying-to-access-array-offset-on-value-of-type-null#p221775
=> V2.4 fix sqlite driver get foreign keys method
